
title = "Gallery"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
[params]
  defaultTheme = "dark"
  title = "Gallery"
  [params.author]
    name = "Valentin Pandenko"
  [params.socialIcons]
    instagram = "https://www.instagram.com/valentin_pandenko/"
    github = "https://github.com/Tumypmyp/art-portfolio/"
    youtube = "https://www.youtube.com/@pandenko"
